# Generated by Django 4.0.4 on 2022-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='water',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='water',
            name='date',
            field=models.DateField(verbose_name='water date'),
        ),
    ]
