# Generated by Django 4.0.4 on 2022-04-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pot_alter_water_options_alter_water_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.pot'),
        ),
    ]
